### PR TITLE
Resolve https://github.com/RKrahl/pytest-dependency/issues/3

### PR DESCRIPTION
**Pull request by selenareneephillips**
The user, @JoeSc,  who originally coded this feature update has since gone silent on GitHub. I would personally like to be able to use this feature, so I forked his repo and created this pull request using his changes.

This should resolve https://github.com/RKrahl/pytest-dependency/issues/3

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
Would really be great if this could be checked and merged.

**Comment by richardhanson** [comment]
@RKrahl would love to see this feature and be able to use it

**Comment by CMCDragonkai** [comment]
Ping @RKrahl

**Comment by CMCDragonkai** [comment]
@RKrahl is there a problem with this PR? Or would prefer we fork pytest-dependency to get this functionality?

**Comment by aaronsewall** [comment]
@selenareneephillips could you rebase or merge master of RKrahl onto your branch so that your fork is usable from pip?

**Comment by marianne-butaye** [comment]
@selenareneephillips @RKrahl  When will this feature be available?

**Comment by selenareneephillips** [comment]
> @selenareneephillips could you rebase or merge master of RKrahl onto your branch so that your fork is usable from pip?

I merged rKrahl master onto my branch.

**Comment by selenareneephillips** [comment]
> @selenareneephillips @RKrahl When will this feature be available?

I merged rKhral's master onto my branch. According to @aaronsewall, this should be usable from pip now.

**Comment by LECbg** [comment]
I ran into this use case too, if this PR could be merged it would be really nice.

**Comment by selenareneephillips** [comment]
@LECbg I merged RKrahl's master onto my branch. So you can take what is on my branch and install it.

**Comment by heatherKoo07** [comment]
hi, is this not merged yet?

**Comment by CMCDragonkai** [comment]
Can add extra maintainers to this package since @RKrahl seems busy?

**Comment by RKrahl** [comment]
First of, my apologies to all for that very long silence.

Many thanks to @JoeSc and @selenareneephillips for your contributions!  However, this PR mingles the scope Issue #3 with the 'depends=all' suggestion from Issue #19.  As already explained in the issue, I'm not very happy with that latter idea.  I'd prefer to consider each issue separately.

I stripped the 'depends=all' stuff from JoeSc's code and will submit that as a new PR.  There might still be minor issues with the remaining changes, but i will deal with that in the new PR.

**Pull request closed without merging**
