### PR TITLE
Avoid using deprecated get_marker function

### PR DESCRIPTION
**Pull request by Rogdham**
Hopefully fixing #24 by following <https://github.com/pytest-dev/pytest/blob/master/doc/en/mark.rst#updating-code>.

Please test thoroughly! I don't know your code base.

***

__*EDIT:*__

To support the new function call, we need to use PyTest version 3.6 (from [this commit](https://github.com/pytest-dev/pytest/commit/4914135fdf45bc4fa0469f2a9d3161c5830e84fd))… in turns, this seems to make it incompatible with Python 3.2.

In this PR, I'm removing support for Python 3.2. I'm not sure if that's ok with you, or if there is a way around that. I've noticed that the [README of the PyTest project](https://github.com/pytest-dev/pytest#features) mentions that it needs Python 3.4+ so there's that.

If you merge this PR, I would suggest bumping the version of pytest-dependency.

### CODE REVIEW

**Comment by Rogdham** [comment]
Hello @RKrahl @greenpasta :wave:
Could you give this a try if you have some time? Thanks!

**Comment by rahulverma** [comment]
Can you please merge this? The warnings clog up the test results.

**Comment by ozars** [comment]
Could you please merge this for next release?

As a temporary solution, you can ignore these warnings by adding this to your pytest config file:
```ini
filterwarnings =
    ignore::DeprecationWarning
```

**Comment by Rogdham** [comment]
@RKrahl :wave: Several people would like this simple PR to be merged, could you give it a look please? :sparkles: 

Feel free to tell me if there are any modifications you would like me to do, or if I can help otherwise.

**Comment by nlsdfnbch** [comment]
@ozars , this will only work if you pin your pytest version.

pytest 4.0.0 now throws an exception when using `get_marker`. Hence, as long as this PR stays unmerged, the project is only compatible with `pytest<4.0.0`.

**Comment by ozars** [comment]
@nlsdfnbch I'm using with pytest 4.0.0 already. I have no issues ignoring deprecation warnings. Raised exception is probably handled by pytest internally to print deprecation warning. It doesn't interfere with tests in my case.

Regardless of this workaround, I agree this PR needs to be merged ASAP. I will send an email to @RKrahl, maybe he isn't aware of this PR somehow.

**Comment by ozars** [comment]
@nlsdfnbch I add above configuration to my `setup.cfg` under `[tool:pytest]`. I didn't try filtering warnings using CLI flags.

**Comment by omercnet** [comment]
+1 please merge !

**Comment by rplevka** [comment]
+1

**Comment by RKrahl** [comment]
Many thanks for the PR and sorry for the delay merging it!

**Pull request merged**
